CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    phone_number VARCHAR(30),
    age INTEGER
);
DELETE FROM customers;
ALTER TABLE customers ALTER COLUMN id RESTART WITH 1;
INSERT INTO customers (name, phone_number, age)
VALUES ('김일번', '010-1111-1111', 15),
       ('이이번', '010-2222-2222', 20),
       ('정삼번', '010-3333-3333', 35);
